# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-15 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20191014_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='post',
            field=models.CharField(max_length=30),
        ),
    ]
